# services:
#   grafana:
#     user: root
#     container_name: 'oxd-svgmodifier-panel'

#     build:
#       context: ./.config
#       args:
#         grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
#         grafana_version: ${GRAFANA_VERSION:-11.3.2}
#         development: ${DEVELOPMENT:-false}
#         anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
#     ports:
#       - 3000:3000/tcp
#     volumes:
#       - ./dist:/var/lib/grafana/plugins/oxd-svgmodifier-panel
#       - ./provisioning:/etc/grafana/provisioning
#       - .:/root/oxd-svgmodifier-panel

# environment:
#   NODE_ENV: development
#   GF_LOG_FILTERS: plugin.oxd-svgmodifier-panel:debug
#   GF_LOG_LEVEL: debug
#   GF_DATAPROXY_LOGGING: 1
#   GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: oxd-svgmodifier-panel

version: '3.0'

services:
  grafana:
    container_name: 'oxd-svgmodifier-panel'
    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.0.1}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/oxd-svgmodifier-panel
      - ./provisioning:/etc/grafana/provisioning
